# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d4e78cc444392bdd80e15bd7b8db1f64bf1755755a919ecc823fe4d492b25898a67753547376e59f6d0966c9d400b4e93e54303336653a133f85d47bc73d952

test:
  secret_key_base: bee5dd35a11ce7ff14b949b32e1e01376cea1640850bc18d478422374e419e5a633cf272b64b3721e714bc08ee6027ace3188dffc70df6f91a6988db28840f5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
